name = "RayTracer"
uuid = "be56bf3c-3fa2-4c2c-974f-c185241bb5ad"
authors = ["Albert Cardenete <albertcardenete95@gmail.com> and contributors"]
version = "0.1.3"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
